spring:
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password:

server:
  port: 9999
  servlet:
    encoding:
      force: true
      charset: UTF-8

beetlsql:
  sqlManagers: sqlManager
  sqlManager:
    ds: dataSource
    basePackage: com.example.mapper
    daoSuffix: Mapper